<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.10.12 on linux)" generated="20231002 10:52:29.383" rpa="false" schemaversion="3">
<suite id="s1" name="Selenium-Robot-Framework" source="/home/nazira/automation/selenium-robot-framework">
<suite id="s1-s1" name="Tests" source="/home/nazira/automation/selenium-robot-framework/tests">
<suite id="s1-s1-s1" name="Somethinc" source="/home/nazira/automation/selenium-robot-framework/tests/Somethinc">
<suite id="s1-s1-s1-s1" name="Homepage" source="/home/nazira/automation/selenium-robot-framework/tests/Somethinc/homepage.robot">
<test id="s1-s1-s1-s1-t1" name="Buka Sometihnc" line="5">
<kw name="Buka Browser" library="homepage">
<kw name="Open Browser" library="SeleniumLibrary">
<arg>browser=${Chrome}</arg>
<arg>url=${Homepage Somethinc}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20231002 10:52:29.494" level="INFO">Opening browser 'Chrome' to base url 'https://somethinc.com/en'.</msg>
<msg timestamp="20231002 10:53:16.867" level="WARN">The version of chrome cannot be detected. Trying with latest driver version</msg>
<msg timestamp="20231002 10:53:17.372" level="INFO">Cannot capture screenshot because no browser is open.</msg>
<msg timestamp="20231002 10:53:17.373" level="FAIL">WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
</msg>
<status status="FAIL" starttime="20231002 10:52:29.494" endtime="20231002 10:53:17.376"/>
</kw>
<kw name="Title Should Be" library="SeleniumLibrary">
<arg>title=${Tittle Homepage}</arg>
<doc>Verifies that the current page title equals ``title``.</doc>
<status status="NOT RUN" starttime="20231002 10:53:17.377" endtime="20231002 10:53:17.377"/>
</kw>
<status status="FAIL" starttime="20231002 10:52:29.493" endtime="20231002 10:53:17.378"/>
</kw>
<status status="FAIL" starttime="20231002 10:52:29.492" endtime="20231002 10:53:17.378">WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
</status>
</test>
<status status="FAIL" starttime="20231002 10:52:29.406" endtime="20231002 10:53:17.379"/>
</suite>
<status status="FAIL" starttime="20231002 10:52:29.404" endtime="20231002 10:53:17.381"/>
</suite>
<status status="FAIL" starttime="20231002 10:52:29.402" endtime="20231002 10:53:17.382"/>
</suite>
<status status="FAIL" starttime="20231002 10:52:29.388" endtime="20231002 10:53:17.382"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Selenium-Robot-Framework">Selenium-Robot-Framework</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="Tests">Selenium-Robot-Framework.Tests</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1-s1" name="Somethinc">Selenium-Robot-Framework.Tests.Somethinc</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1-s1-s1" name="Homepage">Selenium-Robot-Framework.Tests.Somethinc.Homepage</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20231002 10:53:16.867" level="WARN">The version of chrome cannot be detected. Trying with latest driver version</msg>
</errors>
</robot>
